apiVersion: v1
kind: Service
metadata:
  name: lugx-frontend-service
  namespace: lugx-frontend
spec:
  type: LoadBalancer
  selector:
    app: lugx-frontend
  ports:
    - port: 80
      targetPort: 80
